# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-28 06:40
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Assessment_Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=250, null=True)),
                ('abbr', models.CharField(db_index=True, max_length=20, unique=True)),
                ('year', models.CharField(blank=True, db_index=True, help_text='Optional', max_length=4, null=True)),
                ('session', models.CharField(blank=True, db_index=True, help_text='Optional', max_length=20, null=True)),
                ('status', models.BooleanField(db_index=True, default=True)),
                ('start_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='self assess startdate')),
                ('end_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='self assess enddate')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentFormOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': 'assessment_form_options',
            },
        ),
        migrations.CreateModel(
            name='AssessmentFormQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True)),
                ('question_type', models.BigIntegerField(choices=[(1, 'Textarea'), (2, 'Input Box'), (3, 'Radio Input'), (4, 'Checkbox'), (5, 'Dropdown')], db_index=True, default=1)),
                ('status', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': 'assessment_form_questions',
            },
        ),
        migrations.CreateModel(
            name='AssessmentFormSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(db_index=True, default=True)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Assessment_Settings')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': 'assessment_form_section',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('status', models.BooleanField(choices=[(1, 'Active'), (0, 'In-Active')], db_index=True, default=1)),
                ('is_parent', models.BooleanField(db_index=True, default=False)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('status', models.BooleanField(choices=[(1, 'Active'), (0, 'In-Active')], db_index=True, default=1)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('status', models.BooleanField(choices=[(1, 'Active'), (0, 'In-Active')], db_index=True, default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Usertype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, unique=True)),
                ('status', models.BooleanField(choices=[(1, 'Active'), (0, 'In-Active')], db_index=True, default=1)),
                ('link', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('template_folder', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('use_nav_from_template_folder', models.BooleanField(db_index=True, default=True, verbose_name='use nav')),
                ('navbar_template', models.CharField(blank=True, db_index=True, max_length=250, null=True)),
                ('access', models.ManyToManyField(blank=True, db_index=True, related_name='user_access', to='app.Usertype')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Usertype')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Location'),
        ),
        migrations.AddField(
            model_name='assessmentformquestions',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.AssessmentFormSection'),
        ),
        migrations.AddField(
            model_name='assessmentformoptions',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.AssessmentFormQuestions'),
        ),
        migrations.AddField(
            model_name='assessment_settings',
            name='access_users',
            field=models.ManyToManyField(blank=True, db_index=True, help_text='Select Usertypes that can fill the self assessment form', related_name='self_assess_form_users', to='app.Usertype'),
        ),
        migrations.AddField(
            model_name='assessment_settings',
            name='departments',
            field=models.ManyToManyField(blank=True, db_index=True, help_text='Select the departments which will have this assessment enabled', related_name='enable_in_departments', to='app.Department'),
        ),
        migrations.AddField(
            model_name='assessment_settings',
            name='locations',
            field=models.ManyToManyField(blank=True, db_index=True, help_text='Select the locations at which this assessment will be enabled.', related_name='enable_in_location', to='app.Location'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Department'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Designation'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Location'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='usertype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Usertype'),
        ),
    ]
