# Generated by Django 2.0.4 on 2018-07-06 11:21

import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentFormOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name_plural': 'assessment_form_options',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentFormQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True)),
                ('question_type', models.BigIntegerField(choices=[(1, 'Textarea'), (2, 'Input Box'), (3, 'Radio Input'), (4, 'Checkbox'), (5, 'Dropdown')], db_index=True, default=1)),
                ('status', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name_plural': 'assessment_form_questions',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentFormSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name_plural': 'assessment_form_section',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.AddField(
            model_name='assessmentformquestions',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.AssessmentFormSection'),
        ),
        migrations.AddField(
            model_name='assessmentformoptions',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.AssessmentFormQuestions'),
        ),
    ]
