# Generated by Django 2.0.4 on 2018-06-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180625_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='access',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='user_access', to='app.Usertype'),
        ),
        migrations.AddField(
            model_name='usertype',
            name='link',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usertype',
            name='template_folder',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
