# Generated by Django 2.0.4 on 2018-07-06 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180706_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentformsection',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Assessment_Settings'),
        ),
    ]
