# Generated by Django 2.0.4 on 2018-06-25 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180625_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Department'),
        ),
    ]
