# Generated by Django 2.0.4 on 2018-06-25 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_designation_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_parent',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
