# Generated by Django 2.0.4 on 2018-06-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_department_is_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='navbar_template',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='usertype',
            name='use_nav_from_template_folder',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
