# Generated by Django 2.0.4 on 2018-06-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180628_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment_Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=250, null=True)),
                ('abbr', models.CharField(db_index=True, max_length=20, unique=True)),
                ('year', models.CharField(blank=True, db_index=True, max_length=4, null=True)),
                ('session', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('status', models.BooleanField(db_index=True, default=True)),
                ('enable_self_assessment_form', models.BooleanField(db_index=True, default=True, verbose_name='Self Assessment')),
                ('enable_assessment_grade_form', models.BooleanField(db_index=True, default=True, verbose_name='Assessment Grading')),
                ('self_assessment_form_start_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('self_assessment_form_end_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('assessment_grade_start_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('assessment_grade_end_date', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='usertype',
            name='use_nav_from_template_folder',
            field=models.BooleanField(db_index=True, default=True, verbose_name='use nav'),
        ),
        migrations.AddField(
            model_name='assessment_settings',
            name='assessment_graders',
            field=models.ManyToManyField(db_index=True, help_text='Select Usertypes that can fill the self assessment form', related_name='assess_grade_users', to='app.Usertype'),
        ),
        migrations.AddField(
            model_name='assessment_settings',
            name='self_assessment_users',
            field=models.ManyToManyField(db_index=True, help_text='Select Usertypes that can fill the self assessment form', related_name='self_assess_form_users', to='app.Usertype'),
        ),
    ]
