# Generated by Django 2.0.4 on 2018-06-27 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180628_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment_settings',
            name='template_location',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True),
        ),
    ]
