# Generated by Django 2.0.4 on 2018-06-27 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_assessment_settings_template_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessment_settings',
            old_name='template_location',
            new_name='assess_grade_template',
        ),
        migrations.AddField(
            model_name='assessment_settings',
            name='enable_assess_parameters',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Assessment Parameters'),
        ),
        migrations.AddField(
            model_name='assessment_settings',
            name='parameters_end_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='parameters enddate'),
        ),
        migrations.AddField(
            model_name='assessment_settings',
            name='parameters_start_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='parameters startdate'),
        ),
        migrations.AddField(
            model_name='assessment_settings',
            name='parameters_template',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='assessment_settings',
            name='parameters_users',
            field=models.ManyToManyField(db_index=True, help_text='Select Usertypes that can fill the parameters form', related_name='parameter_form_users', to='app.Usertype'),
        ),
        migrations.AddField(
            model_name='assessment_settings',
            name='self_assess_template',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='assessment_settings',
            name='assessment_grade_end_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='assess grade enddate'),
        ),
        migrations.AlterField(
            model_name='assessment_settings',
            name='assessment_grade_start_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='assess grade startdate'),
        ),
        migrations.AlterField(
            model_name='assessment_settings',
            name='self_assessment_form_end_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='self assess enddate'),
        ),
        migrations.AlterField(
            model_name='assessment_settings',
            name='self_assessment_form_start_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='self assess startdate'),
        ),
    ]
