# Generated by Django 2.0.4 on 2018-06-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20180628_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment_settings',
            name='parameters_graders',
            field=models.ManyToManyField(db_index=True, help_text='Select Usertypes that can grade the parameters form', related_name='parameter_grade_users', to='app.Usertype', verbose_name='Parameter Form Graders'),
        ),
        migrations.AlterField(
            model_name='assessment_settings',
            name='enable_assess_parameters',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Assessment Parameters Form'),
        ),
        migrations.AlterField(
            model_name='assessment_settings',
            name='parameters_users',
            field=models.ManyToManyField(db_index=True, help_text='Select Usertypes that can fill the parameters form', related_name='parameter_form_users', to='app.Usertype', verbose_name='Parameter Form Fillers'),
        ),
    ]
